Repository networkservicemesh/networkservicemesh, pull requests merged in 2018-06, with the labels that each got.

#91 Fix informer factory usage
  plugins/crd/crd_queue.go
  plugins/crd/plugin_impl_crd.go
Labels: bug

#103 Use a single shared informer for all CRDs
  plugins/crd/plugin_impl_crd.go
Labels: enhancement

#108 Adding Object store
  flavors/netmesh/netmesh_flavor.go
  plugins/objectstore/networkservices.go
  plugins/objectstore/objectstore_api.go
  plugins/objectstore/objectstore_plugin.go
Labels: work in progress

#117 Create and store events for CRD object operations
  plugins/crd/crd_queue.go
  plugins/crd/plugin_impl_crd.go
  plugins/handler/plugin_impl_handler.go
Labels: bug
